# Generated by Django 3.2.9 on 2021-11-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceusers',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='insuranceusers',
            name='document_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='insuranceusers',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
