# Generated by Django 3.2.9 on 2021-12-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211112_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insuranceusers',
            options={'ordering': ['-last_name'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='insuranceusers',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='insuranceusers',
            name='document_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Номер документа, удостоверяющего личность'),
        ),
        migrations.AlterField(
            model_name='insuranceusers',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='insuranceusers',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='insuranceusers',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='insuranceusers',
            name='phone',
            field=models.CharField(blank=True, max_length=16, verbose_name='Номер телефона'),
        ),
        migrations.DeleteModel(
            name='InsuranceDeals',
        ),
    ]
