# Generated by Django 3.2.9 on 2021-12-06 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance_orders', '0004_auto_20211206_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала действия')),
                ('end_date', models.DateField(verbose_name='Дата окончания действия')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('options', models.ManyToManyField(to='insurance_orders.InsuranceOptions', verbose_name='Выбранные опции')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance_orders.insuranceorders', verbose_name='Предложение')),
            ],
            options={
                'verbose_name': 'Выбранное предложение',
                'verbose_name_plural': 'Выбранные предложения',
            },
        ),
    ]
