# Generated by Django 3.2.9 on 2021-11-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsuranceDeals',
        ),
        migrations.DeleteModel(
            name='PolicyHolders',
        ),
    ]
