# Generated by Django 3.2.9 on 2021-12-06 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_companies', '0002_auto_20211206_0808'),
        ('insurance_orders', '0003_auto_20211115_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zones',
            options={'ordering': ['id'], 'verbose_name': 'Таможенная зона', 'verbose_name_plural': 'Таможенные зоны'},
        ),
        migrations.AlterField(
            model_name='insuranceoptions',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Базовая цена'),
        ),
        migrations.AlterField(
            model_name='insuranceoptions',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за день пребывания'),
        ),
        migrations.AlterField(
            model_name='insuranceoptions',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='insuranceoptions',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Страховая сумма'),
        ),
        migrations.AlterField(
            model_name='insuranceoptions',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='insuranceorders',
            name='available_options',
            field=models.ManyToManyField(to='insurance_orders.InsuranceOptions', verbose_name='Доступные опции'),
        ),
        migrations.AlterField(
            model_name='insuranceorders',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance_companies.insurancecompanies', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='insuranceorders',
            name='franchise',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Франшиза'),
        ),
        migrations.AlterField(
            model_name='insuranceorders',
            name='max_age',
            field=models.IntegerField(verbose_name='Максимальный возраст'),
        ),
        migrations.AlterField(
            model_name='insuranceorders',
            name='min_age',
            field=models.IntegerField(verbose_name='Минимальный возраст'),
        ),
        migrations.AlterField(
            model_name='insuranceorders',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_orders.zones', verbose_name='Зона действия'),
        ),
        migrations.AlterField(
            model_name='zones',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
