# Generated by Django 3.2.9 on 2021-12-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecompanies',
            name='address',
            field=models.CharField(max_length=512, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='insurancecompanies',
            name='bank_details',
            field=models.JSONField(verbose_name='Банковские реквизиты'),
        ),
        migrations.AlterField(
            model_name='insurancecompanies',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='insurancecompanies',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='insurancecompanies',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='insurancecompanies',
            name='website',
            field=models.CharField(max_length=255, verbose_name='Сайт'),
        ),
    ]
